(function( $ ) {
    
    // Extend the autocomplete widget, using our own application namespace.
    $.widget( "app.autocomplete", $.ui.autocomplete, {

        // The _renderItem() method is responsible for rendering each
        // menu item in the autocomplete menu.
        _renderItem: function( ul, item ) {

            // We want the rendered menu item generated by the default implementation.
            var result = this._super( ul, item );

            // If there is logo data, add our custom CSS class, and the specific
            // logo URL.
            if ( item.logo ) {
                result.find( "a" )
                      .addClass( "ui-menu-item-icon" )
                      .css( "background-image", "url(" + item.logo + ")" );
            }

            return result;

        }

    });

})( jQuery );

$(function() {
    
    // Build our autocomplete widget using a source array. Notice that each object
    // in the array has a "logo" property? We can add any properties we want here.
    $( "#lib" ).autocomplete({
        source: [
            {
                label: "AUDI",
                desc: " Audi AG est un constructeur d'automobiles, \n\
                        sportives et de luxe allemand, \n\
                        filiale du groupe Volkswagen appelé VAG \n\
                        qui détient la marque à 99,55 %. \n\
                        Le siège social se situe à Ingolstadt en \n\
                        Bavière",
                logo: "http://www.rw-designer.com/icon-image/1780-256x256x32.png",
            },
            {
                label: "BUGATTI",
                desc: " Bugatti est un constructeur automobile \n\
                        français filiale du groupe Allemand \n\
                        Volkswagen AG. Fondée en 1909 par \n\
                        le constructeur franco-italien Ettore Bugatti.",
                logo: "https://webiconspng.com/wp-content/uploads/2017/09/Bugatti-PNG-Image-15156.png"
            },
            {
                label: "CITROEN",
                desc: " Citroën est un constructeur automobile français. \n\
                        Son nom en forme longue est Automobiles Citroën.\n\
                        L'entreprise a été fondée en 1919 par \n\
                        André Citroën",
                logo: "http://www.rw-designer.com/icon-image/5370-256x256x32.png"
            },
            {
                label: "FIAT",
                desc: " Fiat, acronyme de « Fabbrica Italiana Automobili\n\
                        Torino », est un constructeur automobile \n\
                        italien, basé au Lingotto à Turin. \n\
                        FIAT a été créée le 11 juillet 1899 \n\
                        au Palazzo Bricherasio par trente actionnaires, \n\
                        dont Giovanni Agnelli",
                logo: "http://www.rw-designer.com/icon-image/1930-256x256x8.png"
            },
            {
                label: "BMW",
                desc: " BMW (sigle de Bayerische Motoren Werke en \n\
                        allemand ou « Manufacture bavaroise de moteurs »\n\
                        en français, ou BMW Group en anglais), \n\
                        est une entreprise industrielle allemande \n\
                        constructrice d'automobiles haut-de-gamme, \n\
                        sportives et luxueuses, mais aussi de motos, \n\
                        après avoir été un grand constructeur de moteurs\n\
                        d'avions. L'entreprise a été fondée en 1916 \n\
                        par Gustav Otto et Karl Friedrich Rapp.",
                logo: "https://a.allegroimg.com/s512/035a30/361cebb24ce5bbd5afc35d3ecdfa"
            },
            {
                label: "CHEVROLET",
                desc: " Chevrolet (prononcé en anglais : [ʃɛvrəˈleɪ]), \n\
                        surnommé « Chevy », est une marque d'automobile \n\
                        américaine qui est devenue une division \n\
                        de la compagnie ...",
                logo: "https://vignette.wikia.nocookie.net/thecrew/images/c/ca/Chevrolet-icon.png/revision/latest?cb=20140811122842"
            },
            {
                label: "FERRARI",
                desc: " Ferrari S.p.A. est un constructeur automobile\n\
                        italien installé à Maranello en Italie. \n\
                        Fondée par Enzo Ferrari en 1947, \n\
                        la marque est considérée comme l'une des \n\
                        meilleures marques automobiles de toute ",
                logo: "http://maxcdn.icons8.com/request-idea/upload/2016/10/06/57f5eb98b253d_Ferrari-emblem.jpg"
            },
            {
                label: "BENTLEY",
                desc: "Bentley est un constructeur d'automobiles de luxe\n\
                         et de course basé en Angleterre à Crewe,\n\
                         fondé par Walter Owen Bentley le 18 janvier \n\
                         1919. Depuis 1998, la société fait partie du \n\
                         groupe allemand Volkswagen.",
                logo: "https://vignette.wikia.nocookie.net/thecrew/images/9/93/Bentley-icon.png/revision/latest?cb=20140810141956"
            },
            {
                label: "CADILLAC",
                desc: "Cadillac est un constructeur automobile\n\
                        américain basé à Détroit division du groupe \n\
                        General Motors. Son nom rend hommage au \n\
                        fondateur français de la ville, \n\
                        le Gascon Antoine de Lamothe-Cadillac.",
                logo: "http://www.rw-designer.com/icon-image/1633-256x256x8.png"
            },
            {
                label: "FORD",
                desc: "Ford est un constructeur automobile américain,\n\
                        basé à Dearborn, une banlieue de la ville de \n\
                        Détroit, dans le Michigan",
                logo: "https://vignette.wikia.nocookie.net/thecrew/images/3/36/Ford-icon.png/revision/latest?cb=20140811170311"
            },
            {
                label: "HONDA",
                desc: "Honda Motor Company, Limited, \n\
                        ou plus simplement Honda, est un constructeur \n\
                        d'automobiles, de camions, de motocyclettes, \n\
                        d'ATVs et de scooters ainsi que d'avions \n\
                        d'affaires",
                logo: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAOEAAADhCAMAAAAJbSJIAAAAkFBMVEX///8rKikoJybo6OgDAAAmJSQ4NzcjIiEgHx4SEA4YFhURDw0fHhwVExEaGBf6+vrw8PD29vbDw8ODgoKLiorV1dXg4OC5ubnf398LCAU8OzqSkpEzMjHBwcF8fHtAPz5kY2NMS0qtrazQ0NBsbGufnp5VVFSkpKN2dXVOTk1oZ2deXV2JiIhxcHBFRUSamZnLlPkTAAARX0lEQVR4nO1dDXOySg8VEEG+RG2rqFWrttpa9f//uxdt62Zx8wHSPved4czcmXtvW9hANjnJJqHVatCgQYMGDRo0aNCgQYMGDRo0aNDg/wO9p/XzaDsdHpZv78fFYjLp3IHJZLF4ed8vd8PpajR4dP6pZP10vZp+LLrtLOzGSRR5nuu6dg1wXc/z/SSIu1m77b8cTqvHtPfXwo1Hn8tZOwwSz7Z+F7brJ3HWXRymA+evxHzcLidBHP26bLqgXhL6x93o6bel648OXhz8rXBATD8OZp+D3xMvHX1ksf+PpLtKGWXefP0r+rreWbH3b6X7hu1ni2nt6ro6/vO3B2En0X5do3j9UxC7/1qoIrxs8VyXfFsrqPj6lH87ezjfjyDO/53/c/7ZxY+WvrqbvdRidUaTWHZz2/UubjrM/XSOLIwTz5pNFsf3t/3+Y7Obz4efn58P3/j8HA6H8/nusPlY7nMyNLH8rH0hD0ESea7slm53Ob5XPmffFdws9yBJYh338+l29LweV3XNvfRpPRitXoeb91mUPyxfcOfuw312dZtJzKe3WY/Tu+5jQDpeDwUiWkHnDpOTLjPBLXJlea9PMIidRELLDadVb7Ceie6Qo12nXAoLofXp7qtp0LYtNm9hnb7piifpA7b82WOF6z8YNdQLTP832dYuXo7nrlGcwGAa3LC835jHt9exk/BjFJnkXtYvX6v1abqVFY02YXKjXXY4Knn1w62Abtc/5TG3ZdBdu/MbVPjNxKNsK3dhp6hb/JndLSfi7kZAN375usSL6b7J3Y73FqlxG7ovlx+O3m94ZLuMiA9FAe3w5YcELk0eMl7VLmBrHZokvG6I55ewoE1tub1bFbe476+uajg3PVp/XrN4OU6JSUJwp5Wvb1TblYZU64IVtcMP4G8eTPvffal/IxqVxYoe1G+kH/pr9BZ90ZXTSH/7XqT5AvOjDerP+xn9kpWc4O9sI+0xJBvRlT/0lxQtdCuyMt65W1esdsWjmTEG+o4fL7TVZhJ7UNiE8b7w5s1+OKrMDdF1mN9h8VH2l5pVDHldcvRkRTws/kJxl36hfvK9MUc12Y3BHMJH7u3ZC39oprJ7uvmFJ7P2ZHWbGhOzON/n1l6eoIis4x+0tcvdCthyjJamdvL9ZFZSKzGo4Qks2u4w9nQBmUL3RkVzpOaHm7zWItgVIwMvPgtgmQIlqKgBbRFW8Lpm29ufGCUUbIBSMBKLXMKJ8RUdgGJlVLDYO4JX6B6NF+sZialle7UIdsW7OX2JUIs+WHj0SVx2BPdsiESVe7ORC6oEoSgcJLuIqcqjIrF2QrxE+OBig5W54AORsFbyPTDS7lzCD+QPTmp/JdjKc1cHbdIE+y0kP+Qf7pUKYmq22Ja/w/5CmQfCnEInm6E0zBx6W/bxXqkgzLSb2mTPyk+jPjEFr9B7Q29upt75zWsk330syU9o4Nv1oaBJlS1wsjGe2UEIY63kG6Hd5G4fqJ3YRh42sLguoXJICoy20iWxRfSEfIxq/cibHoOrUunBNSKhiyt2aSC0O5eQIIfqsdgd4y+8CnnBI6KlViKLsCWIsGQ05XVTpdptYz4DeHKSgo3NtjSnCLXVEDy1kVtYEZXUUxIYddABCydTZw52HFwf+UZodw6XMtiKVRt3DGRsbYq89pHIrUbyjdDuc2hB7QTl7mzbIAE4rGMC9hm2SbL75FJAD53sGfl3inV2DTsGBEUJHWKh989qIt8OeixrL8g/VFwPJh1/rgo2N2MykMCmPvI9wLchrV2Krxt2DNzcPs2/kODifNp9l2BXGJPOX3fAQosvKGtpyAVM1VW5BDZuB+hdIgYSgVrs6QGIzm93DFA9PEL5AhbZMN5KDCQTdAZjIVqH68MPbjwipGw4f79gi5EaKy57TGkESrtN69ah4h6/mEV7AtvQZGkhcH98c9lKeEV1hH2Eg6tTv7FJ0HxxujZAqHdd5Bul3fzDB4wyKRgToHnmlCSA+ejy8qdeDVFwD9+GbN4ZbOFijAjsI56h+cYY3yd1kG+cducWkjNlircUlyINLM5I8SXUcQSF5RAuL4YrDVJyFOnHUWkGf2KNS1hH2QlV68UWXyldLPC2FLBpPghCballR/cfQRHb0Iq5P1Z2uEB/nmBwyDo1NLiog3w7RLUgT5qUJyuQdJAUF1gL88nFBZxL5vGMa8hPMQ0BkCuP9MsCF8e/Bixda7HUWAAk4fx19SX314APxVqwDIkYlmxUQKn3eSPeIdwFaGxmSYwgCAJjTQ5IpvliUZx6338WTJZccsQ7pwtAQk0XYb0xn4sgiKMV3UlNcVpviXJdQELNngAfZNvsVSiffG+ZIh4bWqIkgjrwiLX0OAjbmVTIGXhwYdFZaR4Oyuovi+ajM5VE0h8HKOUUxAc49bbuLeKjNoBok7+ZDy/g2bzA3hPUWxCakKCL11niDbVRo22wvkLwDgjqbQlqdgg8klfmiTf0ZJogfcDDDJnGIvrUPrwr9U25e6voxJkraMfuKegz4rI0LSKv//2kK4fBPbrfic7pf+F0lVDbbinMQ/E+p0fvFsEzQkBx0rOEC94TgeAC6lIKrizonehRzOqetClBeM+QFECqY1JXkxAYR0lqnlkJUQRA4onehaL4WrERze1B4yiRkGm5qhpgYFUeP+BS1QUJ4RuHxzKSrC7XNhdV6kPudZhGK0k6VvEtLZiEVbESCaeMOvExgAnPFFW6PDjBZYGEsJ4ESigpi6G51Zm9VylaIFIH3w9OcIyuYnlNQkjDJClPKri4oEoPzZjmM5bMRKg0ho1KKIgN8Lz+z9UrOIwD227I5fTPWNcjIXE69A288A+Dw+xtS5bIE0goucyY5h5Wle6ET2Zv54gFx5Pq4d8lIV5KoFZTMhBOBSMHJOc+iITQlgpisJZDU+/LapblJKSyWz9LtgQSjgUSCrw1Uq+v4ba5hULKWWcLrdPXoUTRvAXkNKLY5yhQqVJh4gP/CmVVyOpsTuM0pSU0tugWkJXg3ylruizhCbNjljAtKyGZ8/u5A5+0u2LOuwqhVgAJoTmH0ZNIQt47W2WIDVqyqkHUDQAk1KInwHkF2R4+uLjAnkmzbky8+SOhJJ2OSQgPZiTLOkm0ykr4pNYFbFDxhUiSHVEbTs9igAWLJGSp9xewxiIdTP7pClFhICYhmMAmkpBJGf2AKvlXmAs8xRmxhOsCCZfgf8P0oEhCvD6ysCiBYmG1/7cXk7gfICGslIQZYZGEa5mWSjra+hPpGLFAwpKUhFpWB7IwkYRjoWLlTpFjWgeR0TpDNHwDSAiz+r1jSQkFwdzPspj82FY2qOkMUWOVklA7q4VnTyIJe+LxP1ZIJlfWbOpCwZecvQIJoa/qAZ4pO3UoMf6yTZjApxKD6GR9uMrj64cLgGfKJORSm3BleDDszEoMK0SamXAJNeUBtEkSHwoyf3BpHiKiMykzTJMvFzpDxYc6QQBFq5IYX8okf0RMjJ7saVZqWqgsa6BifD21DQ4iZJVpRNGQScTMcKA18MvN05QVCKg8jU6BwIJlJT9cXr+IcFMw0b2HrOS0S1ntqsom6hQIREOStCvR5Imuz9pCY/+8kLKiK2RD4VSyWpcQnJ/LOgqEwQWAHUxO30YsXR0rTHyV9RypkxndhAOlk11IGFzoMiZtezOdHmbtoMpEW1FoAR69XtcGziZlykAWDRFCelHlIecyA6G2jy4hOC6T1RmQRUO/A5kbU+8q1hw72FaypnOnBJ+sCTKypSyKXl8KavFkLXa9fyChqOhRcZdY80/AcAg7e8p6i/uRiNalYgi9gAoUgAsPN4l6/d9B6XXpnQvwyFM2MrcM9a4FMuINaoQDXUKYEhZVGUjy+rVCdtLTVw3rvvaDMaAoMqssm9NcIyTlQtrxoa7VsN5KRkzxbuRfgqAqtAVpaaGaGx7qymgbV6FVO2RMBClry7lwp1QJbatCcHG3hCI2+WAuoG1p9dWyLb2qQL3vguysbm8u825ph7psD+kFbNFQ3ZCZB5XaLvaYgUSNrNieLxqqGaLsCugDLsa50DSKpudRbYK/I6GEeIPD5GKwBWN2UZQvKQ+pFYFEs0AEUczdr2E/vuQ0mRjt8CuQ7Z2hGv1RbN9ygIQiYyopGqpVQkm5UGt/NZi3IRKYriV6XMiQT26dXpQklT5oJpoYDhTrNpCHNUAis1Waett+HM6Wn6+vw70dlv56lEixgIG/ZWbTck0l5PQK4wq7nfngqhvO825WLqEoSj2AdNPtW4K9zqITglLBhR2+jQr7KF3djP6nIAot1GmKoZZH60crzgUxgWnC0hB0jIRkZMvJrSRB1lMezKTUcISwpJpdHlzYXYzL9+bi1ygJLUAuxtQPAVmNpL5KnNf3LOJ5jW4/qGKGJKYDpy+mU1k4uVfQ7SzO63sdkm49WjKDI8npqyNzYx+fRlIEGXRhXt/rMM51bItELLcic+cVrKgUELdH0Tt0ZyxhHqOjPCEE4cCQO0CDPejsdHpiyGfZhbWeJflzflBaH+QpzPlxbToxH19gM8U1hKLUw05Qp2+zuiA4mYA+nHf6qSDrTUyUhmD6ii8S8tW4sJ4Esd5aqzifNRUEF4mwD5Ec0vAlIZtaAed99gRjLLCBma98OLI2UFojLDgj4CtVQbEFzg60T8yQH1E4g+1IKDFdga2DZk/EQFaFmBrXg1sr4l4iOuTz+ihLdJIumMfFthaDfgZq5Vu4H2JmE7FFQ3GJARkj5iVymwbOfaQWDl2K5TMRGXdyUWrISY+xzFy50EY9bjrO0l4ik4Pl8vrtUsNMmd41JqcP89PMeT90AQyxYUx8yR5Lhw5VaAYCdY/b/drXkBJSz5i8ftnJbXTeh9Yn0M9gzzi+uYH2gyrv5YIL04eZKNBHPWRoAYktPx3HgQ0s5DxSumio9JQauvOWolgOyE76S/5O2veCPPMXkb4uTEpYfsg+ySCIU4v+EZwqUd8JukJrgIiW6O/RRUPlP45E2maiXGgJ1puJCit7Wl4hwJv+KAkrjBwgz+vwEpgDMMKB0AWPtc/F4yJSyfkq49mpOXdoJwL8rK//Lp2Gp21FK1gie5GapVRlxP4BtzXYmLz+EjwWm8+YXHHSHEF0NP8lZRqqTGol8pNIaOEcwR60S91zqInoeUa/SDzzSl9bJ9yPZ9wqzx5YgV2md7xV/Kiz3d4ZNJXI68taKwsgeklNOf3+Dn783S498b7w5fHEur0AMYen2oxPnLgZvOtoBm9vy/yEhqGuM3b3ragFxL6p9i2PIaoUN9cbvHXhC7dJfonhVGj58LrvuoxEcFFtEi3+yAoqOHjvaq/bwzqrGIyigrF0s84JmFUiuBA1Md7gEeXyMLRwTp1MX1iCGHvBHTtFtbGTeP/6Y5RxEiIZcGgA3pl6dQTj131cPK4KP6qPve0vb5uTvCSYbFbrPjXks+L3j1O0q/GsE7316rAIkqI1ctv3fUhr5RvyTbYXhG1rj3sLb9NTEN7p/KvoPMboc2+1w8DAE4PFvV9+cQyv8VtMarR4O8u6QeLbs87k+PL+tt9/bA673Xw+H16R/8d8tzscPpb7/dv7cTLzQ5wkIRUqXjCt4VvSI6t6Kal9hpvDy+H7fhT5V3z/6/kn+S/YJTqCr1fP3ur5hlZ/mv11ybMEdmBgIVXhzP3/mox2PKv3O9lPw0BaU/AXcLud1/q+J/kNZ+p3/7qLxAzbby+K9Uc1YfSWJP9aSNuLvV3NX6qHeHp9j2987h+K58fecnTPRHQJct7U7YrKJ2qGm2T2YVTjZ5UJ9J8/O+0w8Sq4sEqwXT/I2i+ndQ3evYSUg9flwoq7ie+5vyRpzhU8L0rCZPayW9X6bXo5nMfn03Dztpj5cdauGVngzl72h8/tYPzbG49HP02dX0Ca/qlWNmjQoEGDBg0aNGjQoEGDBg0aNGjQoEGDBv91/A8TNCSPRCpZBQAAAABJRU5ErkJggg=="
            },
            {
                label: "LAMBORGHINI",
                desc: "Lamborghini est un constructeur automobile \n\
                        fondée en 1951 par l'industriel Ferruccio \n\
                        Lamborghini et installé à Sant'Agata Bolognese \n\
                        en Italie",
                logo: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAOEAAADhCAMAAAAJbSJIAAABTVBMVEX///9CQkEhISH+wAj+ySj+67L+1E7+vQD+vAD/zSgAACD/zyj+1VH/zic/QEH/yycwN0IEEiL/2U8PFiH+7bg8PkEAAyAbHSH6xij/xQUqM0M1OkJHRUEACiHXrC8AACWKcCXfsSi2kSV/ZyPMoiYWGiH/3U8yN0AKEyH/7sw4ODf+1HX+y1D+0UX/89yWgkb+14D+353/+vD/5rT+3ZXivUyxkDTAmSefexv+7rv+1WH+zTotLS3+34f+0Wj+2IaBbTofLUPosBHquimsjDVtXzxxXCSYfjhUTj+bgDeQdCQ1MCP+6KfXtUr/6sC0mUe1ixl3Zjunj0dDOiJhVz3PnhNZSiNOQiT/8dX/659kUyTDlRfEpkh2Xh//2mJHOhc6MyHHupNVU0x7clmHcDQUKEPnzoj/44GnnYHluTjWt2KulUengRl2aUPgqhPetuq+AAAaWklEQVR4nO2d+1va2LrHFSKYhBAQIiERFATBrbb1UkDxWqwi2ovV2tHW2T37OGeffabT///Hs961kqwVCCEJeOk8fp9nRq12ho/vu97bWlmMjT3rWc961rOe9axnPetZf2+tvVh8v766sbe0u7usqmGkKBF8qqrLu7tLexur6+8XX6w99kv1pbXf3q/u7S6Ho5NIlMhR5Nv4B8PLu3ur73970qwv3q8uLYcJVl8mNxHY8PLS6vsXjw3TpRfre1vh4GSOpOHdvfUnwfnb+pIKbB5eOIflB3RyUl1a/+3x4NbWX7nBcZzabDZXViKRGKumd0QL89X6wy/PtfWlsDMccK2YUJEe+SU0McNLD0m5uMc50CE0g6yXa0hCg5LbW3wIvPVdCO09bG5kU6z4LCuflJOTu+v3Sre2vtxFxxG7OUMtLCxEIq9fv/727tuHD39+eol13AE1Gj9+fPz6+fPPN2/C/nCjk8v35a89eBy2XC/ZwlTs9btvf77cf9ueSWhaIlGpVHRTynYKq5pEyuWmp4XZaujiZr7z4+tnE/ZxIN9v2fAwXRfbwkLs9bcPL/9q61oCISmKEo+P9+gfoV5lyuUU4p2eTV0cdX4YpAMgt96PEu/Fni2wqHY6MFvs3YeXb8eBDHH1Yg0gZFlTiFTYvul8/DmAczK6N6qKYJHxzmjYbjwE9/rbp78QGzKaO5onQlMAKmwfNT6/caFE3jqK4LrYnHTGQ3CRd3/+FdcqHtn8EBoGreaE0O2Pn/0pJ5vDMq4tW3w25wS6T5fIcop3Nt+EhjmT07NXjc/9KCeXhwo66xYfZ8N7/eGvRAC6QISYsprLHX184ww5OUSKfGUCNiMs3qe2FowuMCGxpXDR+OkEOfkqKOCSAdi0zDc19e7ljKb7WHajI0TKVIXtjgPk5FIwwDMCqJp8gBdPBMTTK8bf/EcZ5ftyuZxhX7kPyJQQ6oWcPAsCuEYAV2KWc44nPAfNuAIFTMX8dSj6Sal0OK6jTytHnbn5o5ubL9NVw/uEzGlyuuzDlClhu9G1JieDhJtdnARN83279Oacip5IIMDL8+OTWrF+OKPjP7xURZ6X+H30VaIoSiJI7QjwcnNHLVGU8ldJ+ELIJT2hIkt++coyRneDmnCFAH5QKgPw4iT0KPu1Ums8PoNeNI8kiQAVn5Fl3N+Llwoi5Emzz4klhJicE+F7sjiHEHOtUvEIEJPVgaCZXOhjdigjrkbxGgS+1zOD+HRtZh8jai2JF4GQMzEu4+OJEoJCxJzc0gghMiH8ez6VOYWf5BGk+CUTmuVlsZ5DgPXG0TZkfPcFmjv9aTFGV30TLps+OvXuoD8f+Y5eU0URPsdoBqHaaknoxZcS8Tb6qjWu5WVO3FcwYer0oiZycmE6WUdfqY2WzMl5ITSLPgChgP5zrenM1e2p4GrLjPDZQlz2TQgm5MCEMa3vmktoMxgxUeA56Rj5o3InmYT84YE2o6KXr+mHPELT8R+WEphQyGSEuszxggBmvhCq8GE7QwmBPtURRQ457baQS/VjnH1jGdEvIF6G4KRTL/V+gHclVdUIIXq1eRRhKmASk1An7plIIONx6Ofgo6oRQuSJDcQ9+wVZEi3HXBH57Xy5i3BOBEfO5dXSfD/EVCcbdCEuTuJSJhJZmOnnoxqHXmM7bhByMvpNaCrHEh60kHtqWgu5IMLHtpyxbFhCOAKBCGWuarffyyFnwhLPi+CsKQdTZrYtQr8l+HrUiKR9nRQvL+lENwnRGotfigzhwcEh+lCvaOjfxQoiPJY48a0GhMnt7Q6sQ6GB/uh7BqoViCp9CNH67aRCyWJ+vndVCpaX+u2IV03C/9gI9QT99JgEEpMQsegnvEXItVoq+gG5HdcRYQ0W6T56xeeaEUthwd4K6AspBT0+jpqYUEimegjlloAI0d9CKcWeMQVzIfoOppgQQunrBMOnnBSsL/Ga42TNJIQ1BivOJOTgc/5YM112XDlHr3hfo/kQwcAXs5mL25vvodkUEHJqqdi56ibkxKsy/KyUDJXrVwLjrdOBCTccCPUaCm6WSdHygpf5VjEJkQfixG4RYoPuK4qDDdE/fAPsgpLkdPkWFznzqVmc/FGdwHUT8vUc/CyfDCVRNcQEHkq4MQLCRJ7nVJMwPi5yrQKxDhCqCOOtyBC28vUWTvKaSXgH6xAijbgN9uhUQ9VDCXlp6hYv3zlCSNRFyMnVnEGI/mYxeW+EMiVEFpFLRV4Gt0WEMvpe65CHD0akqR0kDuCrtobXKBtLReG7iNdWqgORBhFKFqGKsn2vDdF3BYuQfxhCvcbzhyjYSMSG/DHEAxRbeYtQH9fBaudaS5YLkA9L4AIVTCggq4sXmfINgkBJ/XROMgj5opD8ctO9DuG/MGpCp0hjI0RU0t0lxA4FE57gKNPal1jCE+yXKCRJqO/ScOglhFVkPOkQvVARv94UkBqESVSMdRHK+bwsfh9AOIpYaicEBzyA/50O3+BPcPKo3VHChHIAlprR77DPHqA1J94phBDQwE0FVJGqQiYJNsQ1DX71PYSFeZEv1pwIh8wWK/0JFUjuiXMVihZMeIiL7rfHFmHxcr8kkXYCGVfKoy84NTGugykQGizRL5lqA4rV0PcWbi76EwrIwWvyPRFqjoTggJyEY2A7DoS1P8AcBycmIcejFpEDq6HaAEIHZLVzBRPKKMbME/8s4+YQ/jsq7i34H0DI9RCiOh39Fu6FMOZMiItq9L/koKnAhBoKPXXtkOfY/lCsw89rNZGXZV48huoUenyovFGDjKBSR8aPQnnqQniDf8yB0Kra/I5qnOpSlhBqbF5soSACHREiLCbeiuJ+wiTEDb6onpAfT7ytFwr1S6hhlaNGo1ENhaqdUr6Aut7kkSpK6Ec70yE3QqHlTDhrEfqdmg4ghLKbr7W1A96o1lBtram8jsoeCQgL9drh8f6lZnZeSiWRMAYF5WoVz6BSudx0Bn+8bRzOheBFz6JUCPQOhElUozsR5gITvjcJI46EuD6ZUfAfiZeofZfqlUo9n1D2D+/eIhLYXuuzndHTHoQQs1GGpa7mYE4DpF2ExrijhzAZuLfAhNAfTukOhArEC/gU5X2U1w4KYutEV+5QK6XoyoBxeC8hC5uCzgGV4ofFKurxZYsQB18HwlQ2KCHtgOkLNgjjurZ/AHVaAvcLYutQb+vgjzNtL/NGV0JDGWRWxNmot+bLqAMGQgi+DoTlwB3wi36EB9plTRX/MKrp8fHjGQRnkHmaF3shNDirOaEcqjY4EdUGoZyTl2ZOLUK/26WEMIYIqWEw4XELWp9LUeTPMbufvUOfhIaqwk0DrdOkU9WW+RKY0JpELVxaRsQNLsw2eemufp4ItP0UV1K5pI99CqwyBKLMlchLPYRXgSdRdNb21k6IsqBcP6/43l6Dcb+mKZd3tVLxIln2s09h2vKmLla7CMtHFqFPwLExIIR56dQ+SyhLYv4uUfFtvngCxv0qqgIkXub529urqlD1bcoc+htJUWYIU/PBCc2J8NRLhlAsHCtBvDPehq0Z2sHD0KLQOBX6TnpdMOcKYp0SWvNS3xPhMfzXgPCTlRCVu3bA3VEYikOBzYsUE7lDoe+k10Up4QudKlYb1ljfN2HTJPyTpnzfcdOUDnPF/KV2cFkr4FGiBKVoq/5jzj8hZEvr0+QPk7Dpm3DZJPxWCYjFEkIf1YaNNj0hnN7MdxqNzk1KyA3eRBug5FeT0P/OzFJ0hIQJ1DvypUt8ZqqcQqV3MpkaFg4rZ24+Rf1v5b9yGgkHlXKHW2IOtRwn8zdXF9uooxCQpnMe9kLdNP3TDDR7vgmdWuDgSpyIeEKOu0aQJMMGY6FUbxyFBN8lgKXgLT7TIEZGQTiut1E1CzvfssyMfWUYcIut2oUQkDF4e8i0Twv99g/9CXUk7bvDYimfL7RUjthRIrQyL5ZOA+SNENNa+G6enEvvYSEVXa8kkngBZi6ujuYa9YIqGicVboIgDlF4s4XpX4FPeDlq23hxZRRUc9PC6VyJ7HZsB3BUpiwNcKDGKkxf3guhZYaUcKEiM0qNqn/C1FzwstSxbBsVYQalRCYfpi5gnprP+SekJY3/om3ERQ1LiIw216h1bqo50y9h3gszfv+EQ5Q0RlED2eLdCFI+lZ6bh2NeKEvwpS9CCkPCtlIgG+ashB/kdOKGmRCXR5IQDT79RBXNhCiL+bnvKK4KN7Cpw4yXPEsIvLcGslL+1MgI9cQhJ+FEbzHCRnIehr3iUYDyLWelwyDnhOk8cUQJMa4dqyjHZyNLO0ucrbDBH6f9A2YurFAa5Bm+USfESruAQmZ29ywN2spyNvH1AMtwuHTIJsQRpIu4dojWXzZylp7A2tyxI4pXAZw01RgmHY6NqVa6GJ5QUbABdzYnTKWXbIjSXIBAk7ROmKqBCHcNwhGkC6WtwqDmOj1BtbliN+J3/1WblSzCAY4IjzHpYugOUb9EkUVunrGAE+kdmSWE86V+RbdHgyQLI110bV0EtCBiyW7Z+JDOulZigHQxVLJg+6e3QyHG46iyZpegaUTVRggbTP5Uvhmid8IaUTDVCjwC7LYgItyV7Ub0G06HDaVMdzFU7a2fiJy82wvY46a+UyKtu4N0FiAcTIcet+lgKSfAiXTMnvX9ljXTQ4ZSZtw2zDBKP5Q4ecmZcKfLTW/8ualgBRr/gzaiRSuYXgavTBMonmTPnAAnJq673LTmK+vTIU006GOWayMYZODzUE1HEyLZCeW8Lzcd4py+JRpqAgdTDR4WcQikxE271qHqK1/Qmi1ooBkb27JCTdCFqMCx4WwfC06kI3ZCf/M2q/0NbwUmtELNVNB0AWdLuVg/J01vDZMRq0MHGjPUDFPVKDznmO0Nwo2uws3hgYq+ohVN4EDDhpqAE0X8TIZzMiSI9sJNnPMx+Kbbv8EDzdgYZ4aagA2UVpD7JUMie76QOj4Ic5/NZRisOSSyNhGD5Xx8zrRfMnRYif4IrdYp8KPcY2wDFSjnw0Fiuadrsos1oujj5AI9KxSwdSJ6YU2jAi1EOGLkakJkRLbT99MijmYZMjk/0EKESDrAhLYWSrzwng/pMgye70Ew2o/ihRiAECLpABPaq2/ZR/tEh8EBrxswRBdigIwIZ8Ej7ia0L0QfmzNMNhzu5iiaEf/0vRCh9e2f7S0jNqkJfRDSfbXhliFdiAFKUx1e9EATsgvRByEtSodbhkZGxKVp3+eB+wEeDk4VICbpS577Q3o2eKhsCHpvlqa+e0R4AlPeGEzI5Avv+ZA5kzj0jViTVo/oL5qSesYVLd1tRO8tsHXaK/CYjcq6W8FnvsCdYfcyTFtfpyc2drZ2yKd0k0b0asPkEHcpdGvVevDi3JebwlO/pK2glGeqMc9Ib8Sy2WzM+Gb6bCXrL+WXb0fQG5p6YeULf1NTs3FKXy/BYkyn05sTTS5LGo1Y1tiI2tzFKzV9vYX3SUWPNU3u66hyBUi13NRXvoCnaTgZvfqsnN2a2EQ9RBOnBaCNwRUMsE+T3spmV67Bd9MTO5z3QY21JTNU52RqwyprfO0FV+DxPXkHT31luWkmvew1ogFAPAVfgT/OrmxgxjOZ4+ueEOneb8BNJ7sCuil5XF+2D2I43A9DfoD5W1o1vpvloPSBmYZY9HJKkXHSkVwsGA7kpgmJcxK2HcoP+CNNE3jvDYKqmC8PPv1lNb9DFzREe5ab7nt3U+Wt6EiY3YDAsgR9Y9pKE80tLru7CY7alHmuk8tVU26WZCKp/5PBTmLc1HtKJJeAOAjHUliJKJZaiFvXOygcpTG7LMqlxtyNC+L059E6KeOmU95tSJ4g6nXSHYuQQ/lw0xgnytkltGSXkFkRtQoHia5cCK1jsyNyUiaa+tgqrTibkGR8o+2V5d2zDeMXgY/RZuWVWKyJANUvLsUNU5OOIpKCXpi1qfcWilQ0vavwzF6JIib6zRU45w5PmhTmXC+oo43TqJzUeH5mxc8BML3oZENjdNqzM0r8d1MtFmuwAt0fh6KbagGek+mndfPutqkPHlMibDk5mNCoT7MO35N3zn7vCMnqwCdNch9HNL+wyXJTjw0GXF7joJU066RdvwO5eeapaLOe3h5B40SFd/RJrPEUTq1lyNuddZONM2fdFt64/ufggoaJM0F37520aKZEj7HGzIZSvcbuvZBcwUxmtsz+npyqjd0OngjTO+h8P73tKvw7i0RsjwW7EZJAw5cO4KIM1ky4oTB81hpf8OoNXLi0szJ4ilG+GnkyJLLuifRW1xj3gogzcdImUkQouCO4HpeXLAOWUlWhwHMr14MJaT0zgt6XFbnrM+J15mY8E12rkHvrGD+F1qK5i7e3zVwvz0OAgbt4pIHHTeiMbSS9L6tda+bmJWEkcLLglXFyQRijGAo2qB2kG/hy67RK3E/kXGs1LHo6YaRxBvQbTRgeKjd8fyK5jy8+o9pWIgk2dIKomg+uIyMOPjJES9JAJ7tdZdU1Xjba4uCa5E7F8Xi8yDpqFo7R0lE+HZEmi7w0aJebebB5dPWMqfeWEQcfqCXNoWgM5+JajViR/FtGtWnaqmpokk91JL44YPOJtr6TI31rBCLs/CueOgx8iRS+YJcgkgpHreOwCpN+61QivlLIIITLS9zXIc32I04VRKsebqU1RJKFaGZO06R/4NvzoLu3Ng3h9mCGkC+5GnHa4htxqjAUtVbiACPGEyRIWle7wVCKr2ttCecIeWkz1uukxIacW2XKmND/DQpetOHRiPHx/yHZ0Pg9JIrYZ9ta61oW91tQgNPmgtoQbhh030GkU9KRtb5dolnf1YjK//4bz6+NXjLe/h018lLxj/r1hqxq54hjywJkr7EMie6PWVapCUfZVbDao0Z0K92U/4Zshy9Zwiasb6KGUNXm/725JO4r9s4Rrvi0TAS5w4WQBtIRjdh6hUu36MCcaERScyMnvrK5kRUv2zvpzS20NPGBU0viKY2ecCWb2v9dBJKNeyvYqF5ZRoy4dBi4KMX3eWKL3v2+uSXV/ijsTGzhGiDRorW47fA6EPL9n7Ms378Jx4yViI3oUp1qHJsM9ePYTlau/CuWzUKvgWxazpt3uMi2A6WCyrnszdDhxb2tQhBeibiw6d9iwK2YsnpuujHyWZmvJ2ZQj8uT/JERrootfNNsy7bsgFAu9NkFZpqK+zQha8R3/TJGBdVoKr1GCt9Zd6fod/lWi+wK4DdUIbKVocmi2P/8JXOD/n2a0ChssBH7HSGKx+ENAuwX9YF3KomEcf9Sv4UWyhXlYh8npQeE7qmcoSJ1vcvERsvztJqB5ikmW1Fn3J0wlBT6HTdhjs/cR0XKat1K+wuOaR+u1JXurO/EKxObTaONGkzYH53JFPf79oBjxqY3fmePiMMbx8Vn4M5Wxkf/L53ekeyTcv+AmRDtKUaxre2uRZr2v/X6qfafmMxRJ9W+oWbwTIoPSciGmQd449UtGmx6Nva12tnmllWvjeud39MT6TPJfk7FNyDdtg9Hgz9a4V1k7NZ0Kk/1u7P0ZgxfwE589veVibOdLWl/OEJmU/v+6jVWG9bbJE19sCEql2fX1ztZfNU+/npf5LJZkiyGIJym1cx9dU3dwv8zXJ7aJuDxf02sABB+xxn8B+M8H4vJYs1e4fkEZKfc950pTC3St4Jie2H9v8i2vFWSIqPmV5qtk66A5NeENBWOdqfCTbu0PGX8NN4Wt5pwhTfzR/BOq91p0ycg46OjHgK7KEr9lCne9GNUT6uHgzY2fAEy5do9DWectc74KbPIdG1mpsdkwxFWmTh679UMK3zqlMRTW953en/cYQiZXD+Ck6R+RJIi8dN9n6f4fQAm5yjgw6RCKuynUZz3p3ze0OMdMPM9+0g+Clqmb4/o80EFHz5KE0X0YX0Ui8ZTpxJ8FITC18eJo6YWaX3qbyl6BUzOMz76YLmeFZ4t4j4KLUUfx4c9ApYvGAsO+9hIQKlWykBZ0Xu08UiYopnwAdpeZzEpo//oLSjh7M/HSxRUpLQhb1b6wTOiJ0Dh42MmCip8tyLJigsvvZ5z9wKYY1L9kI9QDimyFEm08foMpgfAFFNvP9oiJFqL0mgT8RhQBwOWvzNRJvpoi5CIZEVy0Cbm7Vb6gYCZDAP4OJmQ1SoTUL2VbwMJp98wUeaeZ/hehKMNqW285YxBgLOfn0qUMdWkAdVThToA0FaNjv7kUyCRV4PfZn7BQ1ocYEH2/cQfarY2SEZAxTlj4dNARHcL/mAAHzuMUpGDiyRnLLwcZhIlNBjAh9ij8Kr3fhBdAKc7LOA9HM4LrlUfiC6AcyzgE8gTrPa8I3oEvNfzCEG0RKcaAxD7rkHWRZ9GIrRr14boElG9BJmHHOB71zKL6JI0vAA+wmTNi2yIfVN/3Bnwxy8AaCFGXBEdCdlS7QkDmohGRO1TozoRssX2kwa0I069Szj1i72EmdzPXwawC/G1U0vcQ1guv/mFALsQYzO9g41uwtTprwVo5kXSTEUilz3z/n/YAZNfwoyeZh7s1tIkgzj1V3d5YyecvmXbwcknWMk46RVBbDqXNzbC2YYN8JG2J/yLdBpRA/GbFu9DmJn9agN8oPNAoxAZ9xtHGFFIZeMNfUercvmnDfARh/f+ZbTEpIKbirV1BxsmL8I2wCfV8A4WuWnCnIZP7Ws9NhTmWb4nNbLwpjXjla+YhXjcRpixz9TC4SczdPIhNcqE1KnXMzpDWLWl+XD0cXdfAmuLhFQj3kQMT9128NCHOBd7L9qzLcaFb/jdrlGdlvpqB3xyIxnvMrKGWd/EztFqzAi3YTvgL5UluvUiHGUyY2ThXfvg+2d7iAmP7Bqdx9Ga0WuEI8SMU/msDTDa/BWDqF1GlWrE1FjTZr9fpxJ1k1HfhDkwo53wV6tj+mmtGTXNGGMJo+qv76GmNgwzIkZK+CsniV6ZMZUxYPiXK0QHyDLj39GARGvLlHFy+RdPgn202JzEhxomm49+Rube9OKVGlVf/T3t96xnPetZz3rWs571rGe56f8B60Dd8vpS3/gAAAAASUVORK5CYII="
            },
        ],
        select: function (event, ui){
                $(function (){
                   $('.car_result').css("visibility","visible");
                   $(".car_result > div:first-child img").attr('src',ui.item.logo) 
                   $(".car_result > div:first-child h1").text(ui.item.label);
                   $(".car_result > div:nth-child(2) p").text(ui.item.desc);
                });
        }
    });
});

if (window.parent && window.parent.parent){
      window.parent.parent.postMessage(["resultsFrame", {
        height: document.body.getBoundingClientRect().height,
        slug: "EwwEC"
      }], "*")
    }